replicaCount: 2

image:
  repository: ghcr.io/harsha-cpu/alankrutha-store
  tag: 833e4c75d42562fed23b415ca904e22c31d04ae2
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000