apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alankrutha.fullname" . }}-secret
  labels:
    {{- include "alankrutha.labels" . | nindent 4 }}
type: Opaque
stringData:
  NEXTAUTH_SECRET: {{ .Values.secrets.nextAuthSecret | quote }}
